apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kubelet-reencrypt
  namespace: {{ .Values.configNamespace }}
spec:
  host: kubelet.internal
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 10250
      tls:
        mode: SIMPLE
        insecureSkipVerify: true
