apiVersion: v2
name: nodes-proxy-get-rce-fix
description: A fix using Istio service mesh for the Kubernetes RCE that abuses Nodes/Proxy Get permission.
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: KolTEQ GmbH
    email: hello@kolteq.com
    url: kolteq.com
